<?php if(Mage::getStoreConfig('onestepcheckout/config/enabled')):?>
<?php $color = "#".Mage::getStoreConfig('onestepcheckout/layout/style_cor'); ?>
<?php $botao_color = "#".Mage::getStoreConfig('onestepcheckout/layout/botao_cor');?>
<?php $islogin=0; if(Mage::getSingleton('customer/session')->isLoggedIn()) $islogin=1; ?>
<style type="text/css">
	#loginbox{background:<?php echo $botao_color;?>;padding: 10px;color:#fff;text-decoration: none;border-radius: 5px;}
	div.moip-osc-block-title{border-bottom:4px solid <?php echo $color;?>;}
	.onestepcheckout-numbers{background:<?php echo $color;?>;}
	p.moip-osc-block-title{color:<?php echo $color;?>;}
	.moip-osc-block-title>h3 {color: <?php echo $color;?>;}
	<?php if(!Mage::getStoreConfig('onestepcheckout/layout/site_response')): ?>
		.moip-osc-column.span4.grid12-4 {width: 33%;}
	<?php endif ?>
</style>

	<div class=" row-fluid grid12-12">
		<h1 class="moip-osc-page-tittle"><?php echo $this->__(Mage::getStoreConfig('onestepcheckout/layout/page_titulo'))?></h1>
		<p class="moip-osc-page-content"><?php echo $this->__(Mage::getStoreConfig('onestepcheckout/layout/page_conteudo'))?></p>
	</div>
	<div class="moip-osc-threecolumns moip-osc-checkoutcontainer moip-osc-skin-generic">
		<form id="onestep_form" autocomplete="off" action="<?php echo $this->getUrl('onestepcheckout/index/updateordermethod') ?>" method="POST">
			<div class="moip-osc-column span4  grid12-4">
				
					<div class="moip-osc-block-title">
						<div class="onestepcheckout-numbers onestepcheckout-numbers-1"></div>
						<h3><?php echo $this->__('Billing address');?></h3>
					</div>
					<div class="moip-osc-block-content">
						<div class="billing_start">
							<?php if(!$islogin):?>
								<?php if(Mage::getStoreConfig('onestepcheckout/layout/enable_quicklogin')):?>
								<a id="loginbox" href="#inline1" title=""><?php echo $this->__('Already registered? Click here to login.');?></a>
								<?php endif?>
							<?php endif?>
							<?php echo $this->getChildHtml('billing');?>
							<?php if(Mage::helper('onestepcheckout')->showCouponCode()):?>
										<?php echo $this->getChildHtml('coupon');?>
							<?php endif;?>
						</div>
					</div>
					<?php if(!Mage::helper('onestepcheckout')->onlyProductDownloadable()):	?>
						<?php if(Mage::getStoreConfig('onestepcheckout/config/allowshippingotheraddress')):?>
						<div style="display:none;" id="shipping_show">
							<div class="moip-osc-block-title">
								<div class="onestepcheckout-numbers onestepcheckout-numbers-2" ></div>
								<h3><?php echo $this->__('Shipping address');?></h3>
							</div>
							<div class="moip-osc-block-content">
								<div>
									<?php echo $this->getChildHtml('shipping');?>
								</div>
							</div>
						</div>
						<?php endif; ?>
					<?php endif;?>
				
			</div>
			<div class="moip-osc-column-2 span8 grid12-8">
				<div class="moip-osc-column-container row-fluid grid12-12">
					<div class="shipping-payment">
						<?php if(!Mage::helper('onestepcheckout')->onlyProductDownloadable()):?>
							<div class="moip-osc-column moip-osc-column-middle grid12-6" id="shipping_collum">
								<div class="moip-osc-block" >
									<div class="moip-osc-block-title">
										<div class="onestepcheckout-numbers onestepcheckout-numbers-2" id="moip-osc-p2"></div>
										<h3> <?php echo $this->__('Shipping method');?> </h3>
									</div>
									<div class="moip-osc-block-content">
										<?php echo $this->getChildHtml('shipping_method');?>
										<?php if(Mage::helper('onestepcheckout')->enableGiftMessage()):?>
											<?php echo $this->getChildHtml('additional') ?>
										<?php endif; ?>
									</div>
								</div>
							</div>
						<?php endif?>
						<div class="moip-osc-column  moip-osc-column-right span6 grid12-6" id="payment_collum">
							<div class="moip-osc-block">
								<div class="moip-osc-block-title">
									<div <?php
												if(Mage::helper('onestepcheckout')->onlyProductDownloadable()){
													echo "class='onestepcheckout-numbers onestepcheckout-numbers-2' id='moip-osc-p2'";
												}else{
										          		echo "class='onestepcheckout-numbers onestepcheckout-numbers-3' id='moip-osc-p3'";
												}
									          ?>>
									</div>
									<h3><?php echo $this->__('Payment method');?></h3>
								</div>
								<div class="moip-osc-block-content">
									<?php echo $this->getChildHtml('payment');?>
								</div>
							</div>
						</div>
					</div>

					<div class="review row-fluid grid12-12" id="review_collum">
						<div class="moip-osc-block span12">
							<div class="moip-osc-block-title">
								<div class="onestepcheckout-numbers onestepcheckout-numbers-6"></div>
								<h3><?php echo $this->__('Review your order');?></h3>
							</div>
							<?php echo $this->getChildHtml('review');?>
						</div>
					</div>
					<div id="message-box">
						<?php echo $this->getMessagesBlock()->getGroupedHtml()?>
					</div>
				</div>
			</div>

		</form>
	</div>
<div style="display: none;">
	<div id="inlineerros" style="width:350px;height:280px>px;overflow:auto;">
		<div class="moip-osc-title-login">
			<h1>Ops, corriga os campos a baixo:</h1>
		</div>
		<div class="erros_cadastro">
			<ul class="erros_cadastro_valores">
			</ul>
			<div class="buttons-set">
							<button type="button" class="button" onclick="jQuery.fancybox.close();"><span ><span ><?php echo $this->__('Entendi!') ?></span></span></button>
			</div>
		</div>
	</div>
	<div id="inlinecorreio" style="width:350px;height:280px>px;overflow:auto;">
		<div class="moip-osc-title-login">
			<h1>Busque seu CEP</h1>
		</div>
		<div id="searchForm">
	    	<ul class="form-list" style="width:260px;">
		    	<li class="wide"> 
		    		<label class="required"><em>*</em>Rua, Avenida, travessa...</label>
		    		<div class="input-box">
		    			<input type="text" name="endereco"   id="endereco_de_consulta" value="" class="input-text"/>
		    		</div>
		    	</li>
		    	<li class="field"> 
		    		<label class="required"><em>*</em>Estado</label>
		    		<div class="input-box">
		    			<input type="text" name="uf_busca"   maxlength="2" id="busca_uf" class="input-text" value=""/>
		    		</div>
		    	</li>
		    	<button type="button"  title="Buscar endereço" class="button btn-inline" id="correios_end" onclick="javascript:busca_endereco_correios();"/>
		     	<span><span>Buscar Endereço</span></span></button>
	    	</ul>
	    </div>
	    <div id="resultado">
	    	<ul class="resultados_get_busca"></ul>
	    </div>
	    <div id="buscar_nos_correios">
	    	<h4>Não achou o seu endereço?</h4>
	    	<div><a href="http://www.buscacep.correios.com.br/servicos/dnec/index.do"  target="_blank">Busque direto nos Correios.</a></div>
	    </div>
	    <div style="left: 0px;height:100%; display: none; top:0px;" id="loading-mask2">
				<p id="loading_mask_loader" class="loader"><img alt="Loading..." src="<?php echo $this->getSkinUrl('MOIP/onestepcheckout/images/ajax-loader-tr.gif')?>"><br>Obtendo dados, por favor aguarde...</p>
		</div>
	</div>
	<?php if(!$islogin):?>
		<div id="inline1" style="width:<?php echo Mage::getStoreConfig('onestepcheckout/termcondition/boxwidth')?>px;height:<?php echo Mage::getStoreConfig('onestepcheckout/termcondition/boxheight')?>px;overflow:auto;">
			<div class="moip-osc-ct-term" style="height: <?php echo (Mage::getStoreConfig('onestepcheckout/termcondition/boxheight')-30).'px';?>">
				<?php echo $this->getChildHtml('login');?>
			</div>
		</div>
	<?php endif; ?>
	<?php if(!$islogin):?>
		<div id="inline3" style="width:<?php echo Mage::getStoreConfig('onestepcheckout/termcondition/boxwidth')?>px;height:<?php echo Mage::getStoreConfig('onestepcheckout/termcondition/boxheight')+40?>px;overflow:auto;">
			<div class="moip-osc-ct-term" style="height: <?php echo (Mage::getStoreConfig('onestepcheckout/termcondition/boxheight')+40).'px';?>">
				<?php echo $this->getChildHtml('forgotpassword');?>
			</div>
		</div>
	<?php endif; ?>
	<div id="inline2" style="width:<?php echo Mage::getStoreConfig('onestepcheckout/termcondition/boxwidth')?>px;height:<?php echo Mage::getStoreConfig('onestepcheckout/termcondition/boxheight')?>px;overflow:auto;">
		<div class="moip-osc-title-login">
			<h1><?php echo $this->__('Terms and Conditions');?> </h1>
		</div>
		<div class="moip-osc-ct-term" style="height: <?php echo (Mage::getStoreConfig('onestepcheckout/termcondition/boxheight')-90).'px';?>">
			<?php echo $this->__(Mage::getStoreConfig('onestepcheckout/termcondition/content_options'));?>
		</div>
	</div>
	<div id="store_secure_content" style="width:<?php echo Mage::getStoreConfig('onestepcheckout/termcondition/boxwidth')?>px;height:<?php echo Mage::getStoreConfig('onestepcheckout/termcondition/boxheight')?>px;overflow:auto;">
		<div class="moip-osc-title-login">
			<h1><?php echo $this->__('Loja Segura');?> </h1>
		</div>
		<div class="moip-osc-ct-term" style="height: <?php echo (Mage::getStoreConfig('onestepcheckout/termcondition/boxheight')-90).'px';?>">
			<?php echo $this->__(Mage::getStoreConfig('onestepcheckout/layout/secure'));?>
		</div>
	</div>
</div>
<div style="left: 0px; min-height: 710px; display: none; top:0px;" id="loading-mask">
    <p id="loading_mask_loader" class="loader"><img alt="Loading..." src="<?php echo $this->getSkinUrl('MOIP/onestepcheckout/images/ajax-loader-tr.gif')?>"><br>Atualizando dados, por favor aguarde...</p>
</div>
<?php endif?>
