<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<?php $urldosite = Mage::getBaseUrl('web', true);?>
<script type="text/javascript">
//<![CDATA[
jQuery("#correio").fancybox({
			'titlePosition': 'inside',
			'openEffect': 'elastic',
			'openSpeed': '150',
			'closeEffect': 'elastic',
			'closeSpeed': '150',
			'width': '350px',
			'height': '280px',
});
jQuery(".inline_erros").fancybox({
			'titlePosition': 'inside',
			'openEffect': 'elastic',
			'openSpeed': '150',
			'closeEffect': 'elastic',
			'closeSpeed': '150',
			'width': '350px',
			'height': '280px',
});

jQuery("#loginbox").fancybox({
	'titlePosition': 'inside',
	'openEffect': 'elastic',
	'openSpeed': '150',
	'closeEffect': 'elastic',
	'closeSpeed': '150',
	'width': '<?php echo Mage::getStoreConfig("onestepcheckout/termcondition/boxwidth");?>px',
	'height': '<?php echo Mage::getStoreConfig("onestepcheckout/termcondition/boxheight"); ?>px',
});
jQuery("#onestepcheckout-toc-link").fancybox({
	'titlePosition': 'inside',
	'openEffect': 'elastic',
	'openSpeed': '150',
	'closeEffect': 'elastic',
	'closeSpeed': '150',
});
jQuery("#forgotpassword").fancybox({
	'titlePosition': 'inside',
	'openEffect': 'elastic',
	'openSpeed': '150',
	'closeEffect': 'elastic',
	'closeSpeed': '150',
	'width': '<?php echo Mage::getStoreConfig("onestepcheckout/termcondition/boxwidth");?>px',
	'height': '<?php echo Mage::getStoreConfig("onestepcheckout/termcondition/boxheight")+50; ?>px',
});
jQuery("#backlogin").fancybox({
	'titlePosition': 'inside',
	'openEffect': 'elastic',
	'openSpeed': '150',
	'closeEffect': 'elastic',
	'closeSpeed': '150',
});
jQuery("#store_secure").fancybox({
	'titlePosition': 'inside',
	'openEffect': 'elastic',
	'openSpeed': '150',
	'closeEffect': 'elastic',
	'closeSpeed': '150',
	'width': '<?php echo Mage::getStoreConfig("onestepcheckout/termcondition/boxwidth");?>px',
	'height': '<?php echo Mage::getStoreConfig("onestepcheckout/termcondition/boxheight")+50; ?>px',
});
var message_payment = "<?php echo Mage::helper('onestepcheckout')->__('Please select a payment method for your order!');?>";
var message_ship = "<?php echo Mage::helper('onestepcheckout')->__('Please select a shipping method for your order!');?>";
var updatepaymenttypeurl = "<?php echo Mage::getUrl('onestepcheckout/index/updatepaymenttype')?>";
var updatepaymentmethodurl = "<?php echo Mage::getUrl('onestepcheckout/index/updatepaymentmethod')?>";
var updatecouponurl = "<?php echo Mage::getUrl('onestepcheckout/index/updatecoupon')?>";
var updateqtyurl = "<?php echo Mage::getUrl('onestepcheckout/index/updateqty')?>";
var removeproducturl = "<?php echo Mage::getUrl('onestepcheckout/index/removeproduct')?>";
var updateshippingmethodurl = "<?php echo Mage::getUrl('onestepcheckout/index/updateshippingmethod') ?>";

function ProxCamp(fields) {
	fields.value=soNumeros(fields.value)
	if (fields.value.length == fields.maxLength) {
			for (var i = 0; i < fields.form.length; i++) {
				if (fields.form[i] == fields && fields.form[(i + 1)] && fields.form[(i + 1)].type != "hidden") {
					fields.form[(i + 1)].focus();
				break;
			}
		}
	}
}
function soNumeros(v){
    return v.replace(/\D/g,"")
}
function has_default_billing()
{
	<?php if (Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
		return 1;
	<?php else: ?>
		return 0;
	<?php endif ?>
}
function getval(sel) {
	if (sel.value == 1){
		jQuery('.dados-pj').slideUp();
		jQuery('.dados-pj input:not([type=checkbox])').removeClass('required-entry');
	}else{
		jQuery('.dados-pj').slideDown();
		jQuery('.dados-pj input:not([type=checkbox])').addClass('required-entry');
	}
}
function marcar_isento() {
	jQuery("#insestadual").val("Isento");
}
function seleciona_cep_busca(valor) {
	var cep_buscado = jQuery('.'+valor.className).val();
	jQuery("#billing\\:postcode").val(cep_buscado);
	buscarEndereco('billing');
	jQuery.fancybox.close();
	jQuery("#billing\\:street2").focus();
}
function busca_endereco_correios(){
	var url = '<?php echo  Mage::getUrl("Transparente/Standard/buscaCep/")?>meio/buscaend/logradouro/' + jQuery("#endereco_de_consulta").val().replace(/[^a-zA-ZãéíóúãõàèìòùÀÈÌÙÒÃÂâÁÉÍÓÚ ]/g, '') +'/busca_uf/'+jQuery("#busca_uf").val();
		jQuery.getJSON(url, function (result) {
			for (var i = 0; i < result.length; i++) {
			  jQuery(".resultados_get_busca").append('<label class="busca_end_label"><div class="seletec_result_end"><input type="radio" value="'+result[i].retorno.cep+'" class="cep_encontrado_'+result[i].retorno.cep+'" onclick="javascript:seleciona_cep_busca(this);"></div><div class="dados_result_end"><span class="cidade">'+result[i].retorno.cidade + ' - ' + result[i].retorno.uf+'</span><span class="cep">'+result[i].retorno.cep+'</span><span class="rua">'+result[i].retorno.rua+'</span></div></label>');	
			}
			jQuery("#searchForm").hide();
			jQuery("#buscar_nos_correios").show();
	});
};

function buscarEndereco(whatform) {
	if (whatform == "billing") {
		var campos = {
			postcode: document.getElementById('billing:postcode'),
			street_1: document.getElementById('billing:street1'),
			street_4: document.getElementById('billing:street4'),
			city: document.getElementById('billing:city'),
			region: document.getElementById('billing:region_id')
		};
		
	}
	if (whatform == "shipping") {
		var campos = {
			postcode: document.getElementById('shipping:postcode'),
			street_1: document.getElementById('shipping:street1'),
			street_4: document.getElementById('shipping:street4'),
			city: document.getElementById('shipping:city'),
			region: document.getElementById('shipping:region_id'),
		};
		
	}
	if (whatform == "register") {
		var campos = {
			postcode: document.getElementById('postcode'),
			street_1: document.getElementById('street_1'),
			street_4: document.getElementById('street_4'),
			city: document.getElementById('city'),
			region: document.getElementById('region_id')
		};
	}
	
	jQuery.ajax({
		type:'GET',
		url: '<?php echo $urldosite; ?>Transparente/Standard/buscaCep/meio/cep/cep/' + campos.postcode.value.replace(/\+/g, ''),
		
		beforeSend: function(data){
			jQuery(campos.street_1).val("Buscando Endereço");
			jQuery(campos.street_4).val("Buscando Endereço");
			jQuery(campos.city).val("Buscando Endereço");
		},

		success: function(data){
			jQuery('#loading-mask').fadeOut();
			var addressData = jQuery.parseJSON(data);
			jQuery(campos.street_1).val(addressData.logradouro);
			jQuery(campos.street_4).val(addressData.bairro);
			jQuery(campos.city).val(addressData.cidade);
			jQuery(campos.region).val(addressData.ufid);
			if (campos.postcode != "" && campos.postcode != ".") 
			{
				updateShippingType(campos.postcode);
			};
			jQuery("#billing\\:street2").focus();
		},
		error: function(){
			jQuery(campos.street_1).val("");
			jQuery(campos.street_4).val("");
			jQuery(campos.city).val("");
			jQuery(campos.region).val("");
			if (campos.postcode != "" && campos.postcode != ".") 
			{
				updateShippingType(campos.postcode);
			};
		},
	});
};
function updateShippingMethod() {
	if(document.getElementById('billing:postcode') != "" && document.getElementById('billing:postcode') != "." ){
		jQuery.ajax({
			type: "POST",
			url: updateshippingmethodurl,
			data: jQuery("#onestep_form").serialize(),
			beforeSend: function(){
				jQuery('.validation-advice').hide();
				jQuery("input[name='shipping_method']").removeClass('validation-failed');
				jQuery('#checkout-payment-method-load').html('<div class="update_payment">Calculando valor do pagamento.<img class="Loading" alt="Loading..." src="<?php echo $this->getSkinUrl("MOIP/onestepcheckout/images/ajax-loader-tr.gif")?>"></div>');

			},
			success: function(msg) {
				msg = msg.replace("[]", "");
				jQuery('#checkout-review-load').html(msg);
				updatePaymentAssociated();
			},
			fail:function() {
				updateShippingMethod();
			},
			always: function() {

			},
		})
		
	}
};
function updateShippingType(str_value){
	<?php if(!Mage::helper('onestepcheckout')->onlyProductDownloadable()):?>
		jQuery.ajax({
			async: false,
			type: "POST",
			url: "<?php echo Mage::getUrl('onestepcheckout/index/updateshippingtype')?>",
			data:jQuery("#onestep_form").serialize(),
			beforeSend: function(){
				jQuery('#message-box').html('');
				jQuery('#checkout-shipping-method-load').html('<div class="update_shipping">Calculando Frete.<img class="Loading" alt="Loading..." src="<?php echo $this->getSkinUrl("MOIP/onestepcheckout/images/ajax-loader-tr.gif")?>"></div>');
			},
			success: function(msg){
					jQuery('#checkout-shipping-method-load').html(msg);
				},
			error: function(){
			 	jQuery('#checkout-shipping-method-load').html("Não foi possível cotar o seu frete, por favor recarrege a página ou entre em contato com nossa loja.");
			},
		});
	<?php endif?>
}
function updatePaymentAssociated() {
		jQuery.ajax({
			type: "POST",
			url: updatepaymenttypeurl,
			data: jQuery("#onestep_form").serialize(),
			beforeSend: function(data){
				
			},
			success: function(msg) {
				jQuery('#checkout-payment-method-load').html(msg);
			},
		});
}
function updatePaymentMethod(value) {
	jQuery.ajax({
		url: updatepaymentmethodurl,
		type: "POST",
		data: "payment%5Bmethod%5D=" + value,
		success: function(msg) {
			jQuery('#checkout-review-load').html(msg);	
		},
	});
	
};
function updateCoupon(code, isremove) {
	jQuery.ajax({
		url: updatecouponurl,
		type: "POST",
		data: "coupon_code=" + code + "&remove=" + isremove,
	})
		.done(function(msg) {
			jQuery.ajax({
				url: updatepaymenttypeurl,
				type: "POST",
				data: jQuery("#onestep_form").serialize(),
			});
			jQuery('#checkout-payment-method-load').html();
			str = jQuery.parseJSON(msg);
			jQuery('#tab-coupon').html(str.coupon);
			jQuery('#checkout-review-load').html(str.view);
		})
		.fail(function() {
			updateCoupon(code, isremove);
		})
		.always(function() {
			updateShippingType(document.getElementById('billing:postcode'));
		});
};
function removeProduct(id) {
	hasgift = (typeof(jQuery('#allow-gift-message-container')) != 'undefined') ? 1 : 0;
	
	jQuery.ajax({
		type: "POST",
		url: removeproducturl,
		data: "id=" + id + '&hasgiftbox=' + hasgift,
		beforeSend: function(){
			jQuery('#message-box').html('');
		},
		success: function(msg) {
			jQuery.ajax({
				type: "POST",
				url: updatepaymenttypeurl,
				data: jQuery("#onestep_form").serialize(),
				success: function(msg) {
					jQuery('#checkout-payment-method-load').html(msg);
				}
			});
			str = jQuery.parseJSON(msg);
			if (str.view.search("<script") != 0) {
				if (str.giftbox) {
					jQuery('#checkout-review-load').html(str.view);
					jQuery('#onepage-checkout-shipping-method-additional-load').html(str.giftbox);
				} else {
					jQuery('#checkout-review-load').html(str.view);
				}
			} else {
				jQuery('#checkout-review-load').append(str.view);
			}
		}
	});
	updateShippingType(document.getElementById('billing:postcode'));
}
function logined()
{
	<?php	if(Mage::getSingleton('customer/session')->isLoggedIn()):?>
	return 1;
	<?php else: ?>
	return 0;
	<?php endif ?>
}
function hasaddress(){
	<?php if(count(Mage::getSingleton('customer/session')->getCustomer()->getAddresses())): ?>
	updateShippingType(document.getElementById('billing:postcode'));
	return 1;
	<?php else:?>
	return 0;
	<?php endif; ?>
}
function reDrawOnepage(versao)
{
	if(versao == 2){
	jQuery("#shipping_collum").css({'width':'100%','margin-bottom':'10px'});
	jQuery("#payment_collum").css({'width':'100%', 'float':'left','margin-left': '0'});
	};
	if(versao == 4){
	jQuery('body').addClass('moip-opc-2columns');
	jQuery('.moip-opc-2columns .moip-osc-checkoutcontainer .moip-osc-column-2 .shipping-payment').removeClass('row-fluid');
	jQuery('.moip-opc-2columns .moip-osc-checkoutcontainer .moip-osc-column-2 .shipping-payment').removeClass('grid12-12');
	jQuery('.moip-opc-2columns .moip-osc-checkoutcontainer .moip-osc-column-2 .review').removeClass('row-fluid');
	jQuery('.moip-opc-2columns .moip-osc-checkoutcontainer .moip-osc-column-2 .review').removeClass('grid12-12');
	jQuery('.moip-opc-2columns .moip-osc-checkoutcontainer .moip-osc-column-2 .shipping-payment .moip-osc-column').removeClass('grid12-6');
	jQuery('.moip-opc-2columns .moip-osc-checkoutcontainer .moip-osc-column-2 .shipping-payment .moip-osc-column').removeClass('span6');
	jQuery('.moip-opc-2columns .moip-osc-checkoutcontainer .moip-osc-column-2 .shipping-payment').addClass('grid12-6');
	jQuery('.moip-opc-2columns .moip-osc-checkoutcontainer .moip-osc-column-2 .shipping-payment').addClass('span6');
	jQuery('.moip-opc-2columns .moip-osc-checkoutcontainer .moip-osc-column-2 .shipping-payment .moip-osc-column').addClass('span12');
	jQuery('.moip-opc-2columns .moip-osc-checkoutcontainer .moip-osc-column-2 .shipping-payment .moip-osc-column').addClass('grid12-12');
	jQuery('.moip-opc-2columns .moip-osc-checkoutcontainer .moip-osc-column-2 .review').addClass('span6');
	jQuery('.moip-opc-2columns .moip-osc-checkoutcontainer .moip-osc-column-2 .review').addClass('grid12-6');
	};
}
function removeProductId(product_id){
	if(confirm("<?php echo $this->__('Tem certeza que deseja remover o produto?')?>")){
		removeProduct(product_id);
	}
}
function updateEmailmsg(val){
	jQuery.ajax({
			async:true,
			type: "POST",
			url: "<?php echo Mage::getUrl('onestepcheckout/index/updateemailmsg')?>",
			data:"email="+val,
			beforeSend: function(){
				jQuery('#message-box').html('');
			},
			success: function(msg){
				var error="<div id=\"message-box\"><div  class=\"validation-advice\" style=\"position:relative;\">Email já cadastrado, por favor <a  href=\"#inline1\" id=\"loginbox\">Clique aqui e faça o login</a></div></div>";
				if(msg==0){
					jQuery('#billing\\:email').after(error);
					jQuery('#message-box').html(error);
				}else{
					if(logined()!=1){
						jQuery('#message-box').html('');
					}
					jQuery('#billing\\:email').removeClass('validation-failed');
				}
			}
		});
}
	
jQuery( window ).load(function() {
	<?php if(Mage::helper('onestepcheckout')->onlyProductDownloadable()): ?>
		reDrawOnepage('4');
	<?php endif ?>
	jQuery('#checkout-onepage-buttom').bind("click",function(e){
		jQuery(".btn-checkout").attr("disabled", "disabled");
		jQuery(".btn-checkout").hide();
		jQuery('#co-payment-form').show();
		var form = new VarienForm('onestep_form', true);
		if(!form.validator.validate())	{
			var logic= false;
			if(logined()!=1){
				val=jQuery('#billing\\:email').val();
				emailvalidated=Validation.get('IsEmpty').test(val) || /^([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*@([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*\.(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]){2,})$/i.test(val);
				if(val!="" && emailvalidated){
					updateEmailmsg(val);
				}
			}
		} else 	{
			var logic= true;
			if(logined()!=1){
				var msgerror=1;
				val=jQuery('#billing\\:email').val();
				emailvalidated=Validation.get('IsEmpty').test(val) || /^([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*@([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*\.(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]){2,})$/i.test(val);
				if(val!="" && emailvalidated){
					msgerror=updateEmailmsg(val);
				}
				if(msgerror==0){
					return false;
				}

			}
		}
		if(logic){
			jQuery('#loading-mask').show();
			jQuery('#onestep_form').submit();
			return true;
		} else {
			jQuery('.btn-checkout').after('<a class="inline_erros" href="#inlineerros" style="display:none"></a>');
			jQuery(".erros_cadastro_valores").html("");
			var erro_dado = [];
			var j = 0;
			jQuery(".validation-failed").each(function() {
				j++;
				temp_erro = jQuery(this).attr("title");
				if(jQuery.inArray(temp_erro, erro_dado) != 1){
					erro_dado[j] = jQuery(this).attr("title");
					jQuery(".erros_cadastro_valores").append('<li>'+erro_dado[j]+'</li>');
				}
				jQuery(".inline_erros").trigger( "click" );
			});
			if(jQuery.inArray("Meio de Envio", erro_dado) == 1){
				jQuery('#checkout-shipping-method-loadding').append('<dt><div class="validation-advice" id="advice-required-entry_shipping" style="position:relative;">Você deverá selecionar uma forma de envio.</div></dt>');
			}
		
			jQuery('.validation-advice').delay(3000).fadeOut("slow");
			jQuery(".btn-checkout").removeAttr("disabled");
			jQuery(".btn-checkout").show("slow");
			return false;
		}	
	});
	jQuery('#onestep_form :input').blur(function() {
		if(jQuery(this).attr('id') != "billing:day" && jQuery(this).attr('id') != "billing:month"){
			Validation.validate(jQuery(this).attr('id'));
		}
	});
	jQuery("#billing\\:day").attr('maxlength', '2');
	jQuery("#billing\\:day").attr('onkeyup', 'ProxCamp(this)');
	jQuery("#billing\\:month").attr('maxlength', '2');
	jQuery("#billing\\:month").attr('onkeyup', 'ProxCamp(this)');
	jQuery("#billing\\:year").attr('maxlength', '4');
	jQuery("#billing\\:year").attr('onkeyup', 'ProxCamp(this)');
	if (!logined()) {
		jQuery('#allow-gift-message-container').clearForm();
	}
	jQuery('[id="billing:postcode"]').addClass('required-entry');
	jQuery('[id="shipping:postcode"]').addClass('required-entry');
	jQuery('[id="billing:region_id"]').addClass('validate-select');
	jQuery('[id="shipping:region_id"]').addClass('validate-select');
	<?php if(Mage::getStoreConfig('onestepcheckout/layout/page_layout')==2 || Mage::helper('onestepcheckout')->onlyProductDownloadable() || Mage::getStoreConfig('onestepcheckout/layout/page_layout')==4):?>
		reDrawOnepage("<?php echo Mage::getStoreConfig('onestepcheckout/layout/page_layout'); ?>");
	<?php endif?>
	if (logined()) {
		if (!has_default_billing()) {
			jQuery('#billing-new-address-form').clearForm();
			jQuery('#shipping-new-address-form').clearForm();
		}
	} else {
		jQuery('#billing-new-address-form').clearForm();
		jQuery('#shipping-new-address-form').clearForm();
	}
	<?php
		$islogin=0;
		if(Mage::getSingleton('customer/session')->isLoggedIn()){
			$islogin=1;
		}
	?>
	<?php if($islogin){ 
		$Email_customer = Mage::getSingleton('customer/session')->getCustomer()->getEmail();
		$first_name = Mage::getSingleton('customer/session')->getCustomer()->getFirstname();
		$Last_name = Mage::getSingleton('customer/session')->getCustomer()->getLastname();
		$taxvat =  Mage::getSingleton('customer/session')->getCustomer()->getTaxvat();
	?>
		
		jQuery("#billing\\:email").val("<?php echo $Email_customer; ?>");
		jQuery("#billing\\:firstname").val("<?php echo $first_name; ?>");
		jQuery("#billing\\:lastname").val("<?php echo $Last_name; ?>");
		jQuery("#billing\\:taxvat").val("<?php echo $taxvat; ?>");
	<?php } ?>
	<?php if(!Mage::helper('onestepcheckout')->onlyProductDownloadable()):?>		
			jQuery('#credito_numero').focus(function() {
				if(!jQuery("input[name='shipping_method']:checked").val()){
					jQuery('.form-list.cartao').html("Desculpe, Selecione primeiramente a Forma de Envio no passo 2.");
				} 
			});
	<?php endif?>	
});
//]]>
</script>


