<?php 
/*****/
$sliderConfig = MAGE::helper('ThemeOptionsFlatshop')->getThemeOptionsFlatshop('headerslider');
/*****/


$show = 0;
/**/
if ($sliderConfig['onlyhome']):
if (Mage::getSingleton('cms/page')->getIdentifier() == 'home'  && Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms'):
  $show = 1;
endif;
else:
$show = 1;
endif; 
/**/

if ($sliderConfig ['enabled']):

if ($show): 

if($sliderConfig['slidertype'] == 0){
	$slidesList = explode(",", str_replace(" ", "", $sliderConfig ['slides']));
}else{
	$slidesList = explode(",", str_replace(" ", "", $sliderConfig ['slidesboxed']));
}
?>
<div class="header-slider-holder loading<?php if($sliderConfig['slidertype'] == 1){echo ' boxed-slider';}else{echo ' wide-slider';} ?>">
	<div class="loader"></div>
	<?php if($sliderConfig['slidertype'] == 1): ?>
	<div class="container_12">
		<div class="grid_12">
	<?php endif; ?>
			<div class="header-slider-container">
				<div class="container">
					<div class="iosSlider">
						<div class="slider">
							<?php
								foreach ($slidesList as $slideID) {
									$html = '';
									$html .= '<div class="item" id="item_' . $slideID . '">';
									$html .= $this->getLayout()->createBlock('cms/block')->setBlockId($slideID)->toHtml();
									$html .= '</div>';
									echo $html;
								}
							?>
						</div>
						<?php if($sliderConfig['slidertype'] == 0): ?>
						<div class="container_12">
						<?php endif; ?>
							<div class = 'next'><i class="fa fa-angle-right"></i></div>
							<div class = 'prev unselectable'><i class="fa fa-angle-left"></i></div>
						<?php if($sliderConfig['slidertype'] == 0): ?>
						</div>
						<?php endif; ?>
					</div>
				</div>
			</div>
	<?php if($sliderConfig['slidertype'] == 1): ?>
		</div>
		<div class="clear"></div>
	</div>
	<?php endif; ?>
</div>
<script type="text/javascript">
	/* Slider Preloader */
	var sliderHolder = jQuery('.header-slider-holder');
	var sliderLoader = sliderHolder.find('.loader');
	
	var progress = 0;
	function animateFunc(){
		if(progress > 100){
			return false;
		}
		sliderLoader.html(progress+'%');
		progress+=5;
		setTimeout(animateFunc, 25);
	}
	setTimeout(animateFunc, 25);
	
	function loaded(){
		setTimeout(function(){
		
			img =  jQuery('.header-slider-container .iosSlider .slider .item img:first');
			height = img.height()-7;
			if(img.parent('a').length){
				height = img.parent('a').outerHeight()-7;
			}
			
			if(jQuery('.header-slider-holder.boxed-slider').length){
				height += 42;
			}
			
			sliderLoader.html('');
			sliderLoader.fadeOut(1500, function(){
				jQuery(this).remove();
				sliderHolder.removeClass('loading').css('height', 'auto');
			});
			
			sliderHolder.animate({
			  height: height
			}, 500, "easeOutExpo");
			
		}, 1000);
	}
	
	
  jQuery(window).load(function(){
	/* slider_items_length = jQuery('.slider .item').size();
	if(slider_items_length > 1){
		var slider_bullets = '<ul class="slideSelectors">';
		for(i=1; i<=slider_items_length; i++){
			if(i==1){selected_item = ' selected'}else{selected_item = ''}
			slider_bullets += '<li class="button-item' + selected_item + '" id="item' + i + '">' + i + '</li>'
		}
		slider_bullets += '</ul>';
		jQuery('.header-slider-container .iosSlider .prev').after(slider_bullets);
	} */
  
	//Slider Container Ratio
	var slider_container = jQuery('.header-slider-container .container');
	var slider_img =  jQuery('.header-slider-container .iosSlider .slider .item img:first');
	var ratio = Math.round((slider_img.height()/slider_img.width())*100);
	slider_container.css('padding-bottom', ratio + '%');
	
  
    jQuery('.iosSlider').iosSlider({
      responsiveSlideWidth: true,
      snapToChildren: true,
      desktopClickDrag: true,
      infiniteSlider: true,
      /* navSlideSelector: '.slideSelectors .button-item', */
      navNextSelector: '.iosSlider .next',
      navPrevSelector: '.iosSlider .prev',
      onSlideComplete: slideComplete,
	  onSliderLoaded: sliderLoaded,
	  onSlideChange: slideChange,
      <?php if(isset($sliderConfig ['autoSlide'])): ?>autoSlide: <?php echo $sliderConfig ['autoSlide']; ?><?php endif; ?>
      <?php if(isset($sliderConfig ['autoSlideTimer'])): ?>, autoSlideTimer: <?php echo $sliderConfig ['autoSlideTimer']; ?><?php endif; ?>
	  <?php if(isset($sliderConfig ['autoSlideTransTimer'])): ?>, autoSlideTransTimer: <?php echo $sliderConfig ['autoSlideTransTimer']; endif; ?>
	  <?php if(isset($sliderConfig ['desktopClickDrag'])): ?>, desktopClickDrag: <?php echo $sliderConfig ['desktopClickDrag']; endif; ?>
	  <?php if(isset($sliderConfig ['infiniteSlider'])): ?>, infiniteSlider: <?php echo $sliderConfig ['infiniteSlider']; endif; ?>
    });
    
	
	function slideChange(args) {
	
		/* jQuery('.slideSelectors .button-item').removeClass('selected');
		jQuery('.slideSelectors .button-item:eq(' + (args.currentSlideNumber-1) + ')').addClass('selected'); */
		
	}
	
	function slideComplete(args) {
			/* Slides Animation Presets */
			var slideContainer = [{left: '50%'}, 1000];
			var slideTitle = [{left: '0', opacity: '1'}, 1200]; // example: Animation settings: left = 0, opacity = 100%;  Animation speed: 700ms
			var slideTitle2 = [{left: '0', opacity: '1'}, 1000];
			var slideText = [{left: '0', opacity: '1'}, 1100];
			var slideButton = [{left: '0', opacity: '1'}, 1000];
			
			
			/* Animation Elements */
			/* ===slide container=== */
			jQuery(args.sliderObject).find('.slide-container').attr('style', '');
			jQuery(args.currentSlideObject).find('.slide-container').animate(slideContainer[0], slideContainer[1], 'easeOutQuint');
			/* ========================== */
			
			/* ===slide title element=== */
			jQuery(args.sliderObject).find('h2').attr('style', '');
			jQuery(args.currentSlideObject).find('h2').animate(slideTitle[0], slideTitle[1], 'easeOutQuint');
			/* ========================== */
			
			/* ===slide title 2 element=== */
			jQuery(args.sliderObject).find('h3').attr('style', '');
			jQuery(args.currentSlideObject).find('h3').animate(slideTitle2[0], slideTitle2[1], 'easeOutQuint');
			/* ========================== */
			
			/* ===slide text element=== */
			jQuery(args.sliderObject).find('p').attr('style', '');
			jQuery(args.currentSlideObject).find('p').animate(slideText[0], slideText[1], 'easeOutQuint');
			/* ========================== */
			
			/* ===slide button element=== */
			jQuery(args.sliderObject).find('h5').attr('style', '');
			jQuery(args.currentSlideObject).find('h5').animate(slideButton[0], slideButton[1], 'easeOutQuint');
			/* ========================== */
	}
	
	function sliderLoaded(args) {
		slideComplete(args);
		slideChange(args);
		loaded();
	}
	
	jQuery(window).on('orientationchange', function(e){
		setTimeout(function() {
			jQuery('.iosSlider').iosSlider('update');
		}, 500);
	});
    
  });
</script>
    <?php
  endif;
endif;
if (!$sliderConfig ['enabled'] && $show && $sliderConfig ['staticblock']):
	echo '<div class="header-static"><div class="container_12">' . $this->getLayout()->createBlock('cms/block')->setBlockId($sliderConfig ['staticblock'])->toHtml() . '<div class="clear"></div></div></div>';
endif;