<p>SE VOC&Ecirc; QUER COMPRAR&nbsp;POR ATACADO CADASTRA-SE,&nbsp;PREENCHA OS CAMPOS ABAIXO,&nbsp;QUE ENTRAREMOS EM CONTATO&nbsp;EM SEGUIDA:</p>
<form id="contactForm" action="&lt;?php echo $this-&gt;getFormAction(); ?&gt;" method="post">
	<div class="fieldset">
		<h2 class="legend">Informa&ccedil;&otilde;es</h2>
		<ul class="form-list">
			<li class="fields">
				<div class="field"><label class="required" for="razao"><em>*</em>Raz&atilde;o Social</label>
					<div class="input-box"><input id="razao" class="input-text" type="text" /></div>
				</div>
				<div class="field"><label class="required" for="fantasia"><em>*</em>Nome Fantasia</label>
					<div class="input-box"><input id="fantasia" class="input-text" type="text" /></div>
				</div>
			</li>
			<li class="fields">
				<div class="field"><label class="required" for="contato"><em>*</em>Contato</label>
					<div class="input-box"><input id="contato" class="input-text" type="text" /></div>
				</div>
				<div class="field"><label class="required" for="cnpj"><em>*</em>CNPJ</label>
					<div class="input-box"><input id="cnpj" class="input-text" type="text" /></div>
				</div>
			</li>
			<li class="fields">
				<div class="field"><label class="required" for="uf"><em>*</em>UF</label>
					<div class="input-box"><input id="uf" class="input-text" type="text" /></div>
				</div>
				<div class="field"><label class="required" for="endereco"><em>*</em>Endere&ccedil;o</label>
					<div class="input-box"><input id="endereco" class="input-text" type="text" /></div>
				</div>
			</li>
			<li class="fields">
				<div class="field"><label class="required" for="number"><em>*</em>N&uacute;mero</label>
					<div class="input-box"><input id="number" class="input-text" type="text" /></div>
				</div>
				<div class="field"><label class="required" for="email"><em>*</em>e-mail</label>
					<div class="input-box"><input id="email" class="input-text" type="email" /></div>
				</div>
			</li>
			<li class="fields">
				<div class="field"><label class="required" for="tel"><em>*</em>Telefone</label>
					<div class="input-box"><input id="tel" class="input-text" type="tel" /></div>
				</div>
				<div class="field"><label class="required" for="cel"><em>*</em>Celular</label>
					<div class="input-box"><input id="cel" class="input-text" type="tel" /></div>
				</div>
			</li>
			<li class="wide"><label class="required" for="site"><em>*</em>Website</label>
				<div class="input-box"><input id="site" class="input-text" type="text" /></div>
			</li>
			<li></li>
		</ul>
	</div>
	<div class="buttons-set">
		<p class="required">* Campos Obrigat&oacute;rios</p>
		<button class="button" type="submit"><span><span>Enviar</span></span></button></div>
	</form>