<?php $session = Mage::getSingleton('checkout/session'); ?>
<?php $pgtoArraya = $session->getPgtoarry(); ?>
<?php $result_decode = $session->getResult_decode(); ?>

<div class="corpo_transparente grid12-5 alpha">
	<meta http-equiv='Refresh' content='10;URL=<?php echo $this->getUrlAmbiente()."Instrucao.do?token=". $result_decode['token'] ?>'>
	<div class="method-type bank-title">
		<h3>Transferência Bancária</h3>
		<h4>Você será redirecionado para o seu banco em 10 segundos, caso isto não ocorra, por favor clique no link abaixo para ser redirecionado ao seu banco.</h4>
	</div>
	<p>
			<button type="button" title="Finalizar compra" class="btn-transparente btn-bank" onclick="window.location='<?php echo $this->getUrlAmbiente()."Instrucao.do?token=". $result_decode['token'] ?>'"><img src="<?php echo $this->getSkinUrl('MOIP/transparente/imagem/bank-icon.png') ?>" alt="" />Ir ao Banco</button>
	</p>
</div>
<script type="text/javascript">
//<![CDATA[
				jQuery(document).ready(function(){
					jQuery("#token").val("<?php echo $result_decode['token'] ?>");
					var settings = 
						<?php echo $this->getJson($pgtoArraya); ?>
					;
					MoipWidget(settings);
					
				});
				var sucesso = function(data){
				}
//]]>
</script>