<?php
    $_productCollection = $this->getMyCollection();
    $category = $this->catName();
    $_helper = $this->helper('catalog/output');
    $_collectionSize = $this->productsAmount();
    $_columnCount = 4; //$this->getColumnCount();
    $helpImg = $this->helper('ThemeOptionsFlatshop/images');
    $fancybox = MAGE::helper('ThemeOptionsFlatshop')->getThemeOptionsFlatshop('fancybox' );
?>
<?php // Grid Mode ?>
<div class="home-container grid">
    <div class="meigee-widget">
        <ul class="products-grid widget-grid">
        <?php $i=0; foreach ($_productCollection as $_product): ?>
			<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
			<?php
				$keywords = array('old-price', 'special-price', 'minimal-price-link', 'price-from', 'price-to');
				$pricestring = $this->getPriceHtml($_product, true);
				$isKeyAvaliable = false;
				foreach($keywords as $word){
					if(strpos($pricestring, $word)){
						$isKeyAvaliable = true;
					}
				}
			?>
            <li class="grid_3 item <?php if($isKeyAvaliable == true){echo 'big-price';} ?>">
                <ol class="color-box"><li class="elem first odd"></li><li class="elem even"></li><li class="elem odd"></li><li class="elem even"></li><li class="elem odd last"></li></ol>
				<?php 
					$isKeyAvaliable = false;
					if(MAGE::helper('ThemeOptionsFlatshop')->getProductLabels($_product)){
						$keywords = array('label-new');
						$labelstring = MAGE::helper('ThemeOptionsFlatshop')->getProductLabels($_product);
						foreach($keywords as $word){
							if(strpos($labelstring, $word)){
								$isKeyAvaliable = true;
							}
						}
					}
				?>
				<div class="product-container<?php if(MAGE::helper('ThemeOptionsFlatshop')->getProductLabels($_product)){echo ' labels';} ?>">
					<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
					<div class="product-img-box">
						<?php echo MAGE::helper('ThemeOptionsFlatshop')->getProductLabels($_product); ?>
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><div class="hover-box"><img src="<?php echo $helpImg->getImg($_product, 'small_image', 400, null); ?>" <?php echo MAGE::helper('ThemeOptionsFlatshop/Retina')->getRetinaData('grid', $_product); ?> alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /><?php /* Hover Image */ echo MAGE::helper('ThemeOptionsFlatshop')->getHoverImage($_product, 400, 800); ?></div></a>
						<?php  // Fancybox
						if ($fancybox['fancybox_status'] && $fancybox['fancybox_home'] == 1): ?>
								<a class="fancybox category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>"><i class="fa fa-search"></i></a>
							<?php endif;
						// End Fancybox ?>
						<?php if(Mage::getStoreConfig('ajax/general/enabledpro')){ ?>
						<button type="button" title="<?php echo $this->__('Quick View') ?>" class="button btn-quick-view" onclick="showOptions('<?php echo $_product->getId()?>')"><span><i class="triangle-topleft"></i><i class="triangle-bottomleft"></i><span><?php echo $this->__('Quick View') ?></span></span></button>
						<a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='ajax-fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Test</a>
						<?php } ?>
					</div>
					<div class="actions">
						<?php echo $this->getPriceHtml($_product, true) ?>
						<?php if($_product->isSaleable()): ?>
							<?php if(Mage::getStoreConfig('ajax/general/enabledpro')){ ?>
								<?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
									<div class="button-holder">
										<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
										<span id='ajax_loader<?php echo $_product->getId()?>' class="ajax-loader-item cart-item" style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span>
									</div>
								<?php else: ?>
									<div class="button-holder">
										<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
										<a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='ajax-fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Test</a>
									</div>
								<?php endif; ?>
							<?php }
							else{ ?>
							 <div class="button-holder"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></div>
							<?php } ?>
						<?php else: ?>
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php endif; ?>
						<div class="clear"></div>
					</div>
				</div>
            </li>
        <?php if ($i+1 == $_collectionSize ) break; $i++; endforeach ?>
        </ul> 
    </div>
	<script type="text/javascript">
		jQuery(document).ready(function(){
			jQuery('.ajax-fancybox').fancybox(
				{
				   hideOnContentClick : true,
				   width:600,
				   autoDimensions: true,
				   type : 'iframe',
				   showTitle: false,
				   scrolling: 'no',
				   afterLoad: function(){
						setTimeout(function(){
							var frameBodyHeight = jQuery('.fancybox-iframe').contents().find('body').height();
							if(jQuery(window).height() > frameBodyHeight+30){
								jQuery('.fancybox-inner').css('height', frameBodyHeight);
							}
						}, 1000);
					}
				}
			);
			/* sale label check */
			jQuery('.products-list li.item, .products-grid li.item').each(function(){
				if(!jQuery(this).find('.label-sale').length){
					jQuery(this).addClass('no-sale');
				}
			});
		});
		function showOptions(id){
			jQuery('#fancybox'+id).trigger('click');
		}
		function setAjaxData(data,iframe){
			if(data.status == 'ERROR'){
				alert(data.message);
			}else{
				if(jQuery('.top-cart')){
					jQuery('.top-cart').replaceWith(data.sidebar);
				}
				/* if(jQuery('.header .links')){
					jQuery('.header .links').replaceWith(data.toplink);
				} */
				jQuery.fancybox.close();
				jQuery('body').append('<div class="add-to-cart-success">' + data.message +' <a href="<?php echo $this->getUrl('checkout/cart'); ?>"><br /><span><?php echo $this->__('Go to Shopping Cart') ?></span></a><a href="#" class="btn-remove"><i class="fa fa-times"></i></a></div>');
				setTimeout(function () {jQuery('.add-to-cart-success').slideUp(500)}, 5000);
				jQuery('.add-to-cart-success a.btn-remove').click(function(){
					jQuery(this).parent().slideUp(500);
					return false;
				});
			}
		}
		function setLocationAjax(url,id){
			url += 'isAjax/1';
			url = url.replace("checkout/cart","ajax/index");
			jQuery('#ajax_loader'+id).show();
			try {
				jQuery.ajax( {
					url : url,
					dataType : 'json',
					success : function(data) {
						jQuery('#ajax_loader'+id).hide();
						setAjaxData(data,false);
					}
				});
			} catch (e) {
			}
		}
	</script>
</div>