<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<section class="block-account">
    <header>
        <h2><i class="fa fa-user"></i><?php echo $this->__(Mage::getSingleton('customer/session')->getCustomer()->getFirstname ()).' '.$this->__(Mage::getSingleton('customer/session')->getCustomer()->getLastname ()); ?></h2>
    </header>
    <div class="block-content">
        <ul>
            <?php $_links = $this->getLinks(); ?>
            <?php $_index = 1; ?>
            <?php $_count = count($_links); ?>
            <?php foreach ($_links as $_link): ?>
                <?php $_last = ($_index++ >= $_count); ?>
                <?php if ($this->isActive($_link)): ?>
                    <li class="current<?php echo ($_last ? ' last' : '') ?>"><strong<?php if(strlen($_link->getLabel()) > 20){echo ' class="font-small"';} ?>><i class="fa fa-play"></i><?php echo $_link->getLabel() ?></strong></li>
                <?php else: ?>
                    <li<?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><i class="fa fa-play"></i><?php echo $_link->getLabel() ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</section>