<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<section class="block-subscribe">
    <header>
		<h2><?php echo $this->__('Newsletter') ?></h2>
	</header>
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
        <div class="block-content">
            <label for="newsletter"><?php echo $this->__('Subscribe to be the first to know our about sales, events and special offers!') ?></label>
			<div class="input-box">
                <input type="text" name="email" id="newsletter" title="<?php echo $this->__('Sign up for our newsletter') ?>" value="<?php echo $this->__('Sign up for our newsletter') ?>" onblur="if (this.value=='') this.value = '<?php echo $this->__('Sign up for our newsletter') ?>'" onfocus="if (this.value=='<?php echo $this->__('Sign up for our newsletter') ?>') this.value = ''" class="input-text required-entry validate-email" />
            </div>
			<div class="actions">
				<button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
			</div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
    </script>
</section>